-- Reconciliation marker for a migration already applied by the Lovable project.
-- The remote migration history contains version 20260728051124; this marker keeps
-- the backend deploy pipeline aligned without replaying pricing changes.
