/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VencimentosRouteImport } from './routes/vencimentos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as ManutencoesRouteImport } from './routes/manutencoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterValoresPlanosRouteImport } from './routes/master.valores-planos'
import { Route as MasterUsuariosAtivosRouteImport } from './routes/master.usuarios-ativos'
import { Route as MasterRecursosPlanosRouteImport } from './routes/master.recursos-planos'
import { Route as MasterProximosPagamentosRouteImport } from './routes/master.proximos-pagamentos'
import { Route as MasterPlanosRouteImport } from './routes/master.planos'
import { Route as MasterInadimplentesRouteImport } from './routes/master.inadimplentes'
import { Route as MasterFinanceiroRouteImport } from './routes/master.financeiro'
import { Route as MasterEmpresasRouteImport } from './routes/master.empresas'
import { Route as MasterAssinaturasRouteImport } from './routes/master.assinaturas'
import { Route as EquipamentosIdRouteImport } from './routes/equipamentos.$id'

const VencimentosRoute = VencimentosRouteImport.update({
  id: '/vencimentos',
  path: '/vencimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencoesRoute = ManutencoesRouteImport.update({
  id: '/manutencoes',
  path: '/manutencoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterValoresPlanosRoute = MasterValoresPlanosRouteImport.update({
  id: '/master/valores-planos',
  path: '/master/valores-planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterUsuariosAtivosRoute = MasterUsuariosAtivosRouteImport.update({
  id: '/master/usuarios-ativos',
  path: '/master/usuarios-ativos',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRecursosPlanosRoute = MasterRecursosPlanosRouteImport.update({
  id: '/master/recursos-planos',
  path: '/master/recursos-planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProximosPagamentosRoute =
  MasterProximosPagamentosRouteImport.update({
    id: '/master/proximos-pagamentos',
    path: '/master/proximos-pagamentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterPlanosRoute = MasterPlanosRouteImport.update({
  id: '/master/planos',
  path: '/master/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterInadimplentesRoute = MasterInadimplentesRouteImport.update({
  id: '/master/inadimplentes',
  path: '/master/inadimplentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterFinanceiroRoute = MasterFinanceiroRouteImport.update({
  id: '/master/financeiro',
  path: '/master/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterEmpresasRoute = MasterEmpresasRouteImport.update({
  id: '/master/empresas',
  path: '/master/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAssinaturasRoute = MasterAssinaturasRouteImport.update({
  id: '/master/assinaturas',
  path: '/master/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIdRoute = EquipamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EquipamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/login': typeof LoginRoute
  '/manutencoes': typeof ManutencoesRoute
  '/pendencias': typeof PendenciasRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/vencimentos': typeof VencimentosRoute
  '/equipamentos/$id': typeof EquipamentosIdRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/financeiro': typeof MasterFinanceiroRoute
  '/master/inadimplentes': typeof MasterInadimplentesRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/proximos-pagamentos': typeof MasterProximosPagamentosRoute
  '/master/recursos-planos': typeof MasterRecursosPlanosRoute
  '/master/usuarios-ativos': typeof MasterUsuariosAtivosRoute
  '/master/valores-planos': typeof MasterValoresPlanosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/login': typeof LoginRoute
  '/manutencoes': typeof ManutencoesRoute
  '/pendencias': typeof PendenciasRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/vencimentos': typeof VencimentosRoute
  '/equipamentos/$id': typeof EquipamentosIdRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/financeiro': typeof MasterFinanceiroRoute
  '/master/inadimplentes': typeof MasterInadimplentesRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/proximos-pagamentos': typeof MasterProximosPagamentosRoute
  '/master/recursos-planos': typeof MasterRecursosPlanosRoute
  '/master/usuarios-ativos': typeof MasterUsuariosAtivosRoute
  '/master/valores-planos': typeof MasterValoresPlanosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/login': typeof LoginRoute
  '/manutencoes': typeof ManutencoesRoute
  '/pendencias': typeof PendenciasRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/vencimentos': typeof VencimentosRoute
  '/equipamentos/$id': typeof EquipamentosIdRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/financeiro': typeof MasterFinanceiroRoute
  '/master/inadimplentes': typeof MasterInadimplentesRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/proximos-pagamentos': typeof MasterProximosPagamentosRoute
  '/master/recursos-planos': typeof MasterRecursosPlanosRoute
  '/master/usuarios-ativos': typeof MasterUsuariosAtivosRoute
  '/master/valores-planos': typeof MasterValoresPlanosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/assistente'
    | '/auditoria'
    | '/configuracoes'
    | '/dashboard'
    | '/definir-senha'
    | '/documentos'
    | '/equipamentos'
    | '/login'
    | '/manutencoes'
    | '/pendencias'
    | '/planos'
    | '/relatorios'
    | '/usuarios'
    | '/vencimentos'
    | '/equipamentos/$id'
    | '/master/assinaturas'
    | '/master/empresas'
    | '/master/financeiro'
    | '/master/inadimplentes'
    | '/master/planos'
    | '/master/proximos-pagamentos'
    | '/master/recursos-planos'
    | '/master/usuarios-ativos'
    | '/master/valores-planos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/assistente'
    | '/auditoria'
    | '/configuracoes'
    | '/dashboard'
    | '/definir-senha'
    | '/documentos'
    | '/equipamentos'
    | '/login'
    | '/manutencoes'
    | '/pendencias'
    | '/planos'
    | '/relatorios'
    | '/usuarios'
    | '/vencimentos'
    | '/equipamentos/$id'
    | '/master/assinaturas'
    | '/master/empresas'
    | '/master/financeiro'
    | '/master/inadimplentes'
    | '/master/planos'
    | '/master/proximos-pagamentos'
    | '/master/recursos-planos'
    | '/master/usuarios-ativos'
    | '/master/valores-planos'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/assistente'
    | '/auditoria'
    | '/configuracoes'
    | '/dashboard'
    | '/definir-senha'
    | '/documentos'
    | '/equipamentos'
    | '/login'
    | '/manutencoes'
    | '/pendencias'
    | '/planos'
    | '/relatorios'
    | '/usuarios'
    | '/vencimentos'
    | '/equipamentos/$id'
    | '/master/assinaturas'
    | '/master/empresas'
    | '/master/financeiro'
    | '/master/inadimplentes'
    | '/master/planos'
    | '/master/proximos-pagamentos'
    | '/master/recursos-planos'
    | '/master/usuarios-ativos'
    | '/master/valores-planos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AssistenteRoute: typeof AssistenteRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  DocumentosRoute: typeof DocumentosRoute
  EquipamentosRoute: typeof EquipamentosRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManutencoesRoute: typeof ManutencoesRoute
  PendenciasRoute: typeof PendenciasRoute
  PlanosRoute: typeof PlanosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
  VencimentosRoute: typeof VencimentosRoute
  MasterAssinaturasRoute: typeof MasterAssinaturasRoute
  MasterEmpresasRoute: typeof MasterEmpresasRoute
  MasterFinanceiroRoute: typeof MasterFinanceiroRoute
  MasterInadimplentesRoute: typeof MasterInadimplentesRoute
  MasterPlanosRoute: typeof MasterPlanosRoute
  MasterProximosPagamentosRoute: typeof MasterProximosPagamentosRoute
  MasterRecursosPlanosRoute: typeof MasterRecursosPlanosRoute
  MasterUsuariosAtivosRoute: typeof MasterUsuariosAtivosRoute
  MasterValoresPlanosRoute: typeof MasterValoresPlanosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vencimentos': {
      id: '/vencimentos'
      path: '/vencimentos'
      fullPath: '/vencimentos'
      preLoaderRoute: typeof VencimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencoes': {
      id: '/manutencoes'
      path: '/manutencoes'
      fullPath: '/manutencoes'
      preLoaderRoute: typeof ManutencoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/valores-planos': {
      id: '/master/valores-planos'
      path: '/master/valores-planos'
      fullPath: '/master/valores-planos'
      preLoaderRoute: typeof MasterValoresPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/usuarios-ativos': {
      id: '/master/usuarios-ativos'
      path: '/master/usuarios-ativos'
      fullPath: '/master/usuarios-ativos'
      preLoaderRoute: typeof MasterUsuariosAtivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/recursos-planos': {
      id: '/master/recursos-planos'
      path: '/master/recursos-planos'
      fullPath: '/master/recursos-planos'
      preLoaderRoute: typeof MasterRecursosPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/proximos-pagamentos': {
      id: '/master/proximos-pagamentos'
      path: '/master/proximos-pagamentos'
      fullPath: '/master/proximos-pagamentos'
      preLoaderRoute: typeof MasterProximosPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/planos': {
      id: '/master/planos'
      path: '/master/planos'
      fullPath: '/master/planos'
      preLoaderRoute: typeof MasterPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/inadimplentes': {
      id: '/master/inadimplentes'
      path: '/master/inadimplentes'
      fullPath: '/master/inadimplentes'
      preLoaderRoute: typeof MasterInadimplentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/financeiro': {
      id: '/master/financeiro'
      path: '/master/financeiro'
      fullPath: '/master/financeiro'
      preLoaderRoute: typeof MasterFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/empresas': {
      id: '/master/empresas'
      path: '/master/empresas'
      fullPath: '/master/empresas'
      preLoaderRoute: typeof MasterEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/assinaturas': {
      id: '/master/assinaturas'
      path: '/master/assinaturas'
      fullPath: '/master/assinaturas'
      preLoaderRoute: typeof MasterAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$id': {
      id: '/equipamentos/$id'
      path: '/$id'
      fullPath: '/equipamentos/$id'
      preLoaderRoute: typeof EquipamentosIdRouteImport
      parentRoute: typeof EquipamentosRoute
    }
  }
}

interface EquipamentosRouteChildren {
  EquipamentosIdRoute: typeof EquipamentosIdRoute
}

const EquipamentosRouteChildren: EquipamentosRouteChildren = {
  EquipamentosIdRoute: EquipamentosIdRoute,
}

const EquipamentosRouteWithChildren = EquipamentosRoute._addFileChildren(
  EquipamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AssistenteRoute: AssistenteRoute,
  AuditoriaRoute: AuditoriaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  DocumentosRoute: DocumentosRoute,
  EquipamentosRoute: EquipamentosRouteWithChildren,
  LoginRoute: LoginRoute,
  ManutencoesRoute: ManutencoesRoute,
  PendenciasRoute: PendenciasRoute,
  PlanosRoute: PlanosRoute,
  RelatoriosRoute: RelatoriosRoute,
  UsuariosRoute: UsuariosRoute,
  VencimentosRoute: VencimentosRoute,
  MasterAssinaturasRoute: MasterAssinaturasRoute,
  MasterEmpresasRoute: MasterEmpresasRoute,
  MasterFinanceiroRoute: MasterFinanceiroRoute,
  MasterInadimplentesRoute: MasterInadimplentesRoute,
  MasterPlanosRoute: MasterPlanosRoute,
  MasterProximosPagamentosRoute: MasterProximosPagamentosRoute,
  MasterRecursosPlanosRoute: MasterRecursosPlanosRoute,
  MasterUsuariosAtivosRoute: MasterUsuariosAtivosRoute,
  MasterValoresPlanosRoute: MasterValoresPlanosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
